macro(groupCMakeFiles)
    set_property(TARGET ${ARGV0} PROPERTY PREDEFINED_TARGETS_FOLDER "cmake")
    file(GLOB_RECURSE unityFiles  CONFIGURE_DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/${ARGV0}.dir/Unity/*.cxx")
    source_group("cmake" FILES ${unityFiles})
    source_group("cmake" FILES "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/${ARGV0}.dir/cmake_pch.cxx")
    source_group("cmake" FILES "CMakeLists.txt")
    foreach(configType ${CMAKE_CONFIGURATION_TYPES})
        source_group("cmake" FILES "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/${ARGV0}.dir/${configType}/cmake_pch.hxx")
    endforeach()
endmacro(groupCMakeFiles) 